Repository TOOK-SCAN/TOOK-SCAN-Backend, pull requests merged in 2025-02, with the labels that each got.

#99 ✨ Feature - 4.2.11 (관리자) 주문 상세 간단 조회 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminOrderBriefResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderBriefService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminOrderBriefUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/type/EOrderStatus.java
Labels: ✨ Feature

#101 ✨ Feature - 4.4.1 (관리자) 주문 상세 상품 수정 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrderDocumentsRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrderDocumentsService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/UpdateAdminOrderDocumentsUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Document.java
  src/main/java/com/tookscan/tookscan/order/domain/service/DocumentService.java
  src/main/java/com/tookscan/tookscan/order/repository/DocumentRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DocumentJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DocumentRepositoryImpl.java
Labels: ✨ Feature

#103 ✨ Feature - 4.5.2 (관리자) 상품 일괄 삭제 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteAdminDocumentsService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/DeleteAdminDocumentsUseCase.java
  src/main/java/com/tookscan/tookscan/order/repository/DocumentRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DocumentRepositoryImpl.java
Labels: ✨ Feature

#108 ✨ Feature -4.3.8 (관리자) 운송장 번호 등록 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/DeleteAdminOrdersRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrderDeliveryTrackingNumberRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteAdminOrdersService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrderDeliveryTrackingNumberService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/DeleteAdminOrdersUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/UpdateAdminOrderDeliveryTrackingNumberUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/service/DeliveryService.java
Labels: ✨ Feature

#110 ✨ Feature - 2주 지난 주문 자동 삭제 스케줄러 구현
  src/main/java/com/tookscan/tookscan/TookscanApplication.java
  src/main/java/com/tookscan/tookscan/order/application/scheduler/DeleteOldOrdersScheduler.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteOldOrdersService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/DeleteOldOrdersUseCase.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
Labels: ✨ Feature

#112 ✨ Feature - 4.3.8 (관리자) 운송장 번호 일괄 등록 API 구현
  build.gradle
  src/main/java/com/tookscan/tookscan/core/utility/ExcelUtils.java
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/DeleteAdminDocumentsRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteAdminDocumentsService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrdersDeliveriesTrackingNumberService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/DeleteAdminDocumentsUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/UpdateAdminOrdersDeliveriesTrackingNumberUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
Labels: ✨ Feature

#117 ✨ Feature - 4.2.13 (관리자) 배송 리스트 요약 조회 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminDeliveriesSummariesResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminDeliveriesSummariesService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminDeliveriesSummariesUseCase.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
Labels: ✨ Feature

#118 ✨ Feature - 4.2.14 (관리자) 배송 리스트 조회 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminDeliveriesOverviewsResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminDeliveriesOverviewsService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminDeliveriesOverviewsUseCase.java
Labels: ✨ Feature

#129 🐞 BugFix - NO_NEED_URL에 Oauth 관련 url이 없어 발생하는 버그 해결
  src/main/java/com/tookscan/tookscan/core/constant/Constants.java
Labels: 🐞 BugFix

#134 🐞 BugFix - Oauth 로그인 시 Map에 null이 포함하여 발생하던 버그 수정
  src/main/java/com/tookscan/tookscan/core/utility/HttpServletUtil.java
  src/main/java/com/tookscan/tookscan/security/application/service/LoginOauthService.java
  src/main/java/com/tookscan/tookscan/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/tookscan/tookscan/security/info/GoogleOauth2UserInfo.java
  src/main/java/com/tookscan/tookscan/security/info/factory/Oauth2UserInfoFactory.java
Labels: 🐞 BugFix

#136 ✨ Feature - 2.2.2 계정 간단 조회에 GUEST 반환 추가
  src/main/java/com/tookscan/tookscan/security/domain/type/ESecurityRole.java
  src/main/java/com/tookscan/tookscan/security/filter/JsonWebTokenAuthenticationFilter.java
Labels: ✨ Feature

#138 ✨ Feature - 4.1.6 (관리자) 스캔 시작 API 구현
  src/main/java/com/tookscan/tookscan/core/exception/error/ErrorCode.java
  src/main/java/com/tookscan/tookscan/core/utility/RestClientUtil.java
  src/main/java/com/tookscan/tookscan/core/utility/S3Util.java
  src/main/java/com/tookscan/tookscan/core/utility/ScannerUtil.java
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminDocumentsPdfsResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminDocumentsScanStatusResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminOrderDocumentsOverviewsResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateAdminDocumentsPdfService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminDocumentsPdfsService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminDocumentsScanStatusService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderDocumentsOverviewsService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/CreateAdminDocumentsPdfUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminDocumentsPdfsUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminDocumentsScanStatusUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Document.java
Labels: ✨ Feature

#139 ✨ Feature - 4.1.3 (관리자) 배송 리스트 내보내기 API 구현
  src/main/java/com/tookscan/tookscan/core/utility/ExcelUtils.java
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/ExportAdminDeliveriesRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/ExportAdminDeliveriesService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrdersDeliveriesTrackingNumberService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ExportAdminDeliveriesUseCase.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
Labels: ✨ Feature

#144 🔨 Refactor - API 전체 유효성 검증 추가
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/dto/request/CreateAdminGroupRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/CreateAdminUserGroupRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/DeleteAdminUserRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateAdminGroupRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateAdminUserRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateUserUserRequestDto.java
  src/main/java/com/tookscan/tookscan/core/utility/RestClientUtil.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/CreateAdminOrderMemoRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/CreateGuestOrderRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/CreateUserOrderRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/DeleteAdminDocumentsRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/DeleteAdminOrdersRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/ExportAdminDeliveriesRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrderDeliveryRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrderDeliveryTrackingNumberRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrderDocumentsRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrdersStatusRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrdersDeliveriesTrackingNumberService.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/AdminSignUpDefaultRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/ReadSerialIdAndProviderRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/ReissuePasswordRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/SignUpDefaultRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/SignUpOauthRequestDto.java
  src/main/java/com/tookscan/tookscan/term/application/dto/request/CreateAdminTermRequestDto.java
  src/main/java/com/tookscan/tookscan/term/application/dto/request/UpdateAdminTermRequestDto.java
Labels: 🔨 Refactor

#146 🐞 BugFix - 약관 조회에서 헤더를 요구하는 버그 수정
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateUserUserRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/UpdateUserUserService.java
  src/main/java/com/tookscan/tookscan/account/domain/User.java
  src/main/java/com/tookscan/tookscan/account/domain/service/UserService.java
  src/main/java/com/tookscan/tookscan/core/constant/Constants.java
  src/main/java/com/tookscan/tookscan/core/utility/DateTimeUtil.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderGuestQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderUserQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/CreateGuestOrderResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/CreateUserOrderResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadGuestOrderSummaryResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadUserOrderSummaryResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateGuestOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateUserOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadGuestOrderSummaryService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderSummaryService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadGuestOrderSummaryUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadUserOrderSummaryUseCase.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/SignUpDefaultRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/SignUpOauthRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpDefaultService.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpOauthService.java
Labels: 🐞 BugFix

#148 🔨 Refactor - API 전체 유효성 검증 로직 통일
  src/main/java/com/tookscan/tookscan/account/repository/mysql/GroupRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/core/exception/error/ErrorCode.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderGuestQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderUserQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/domain/service/OrderService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ValidateAuthenticationCodeService.java
  src/main/java/com/tookscan/tookscan/security/repository/mysql/AccountRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/AuthenticationCodeRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/term/application/service/ReadAdminTermOverviewService.java
  src/main/java/com/tookscan/tookscan/term/application/service/ReadUserTermOverviewService.java
  src/main/java/com/tookscan/tookscan/term/repository/TermRepository.java
  src/main/java/com/tookscan/tookscan/term/repository/mysql/TermRepositoryImpl.java
Labels: 🔨 Refactor

#152 ✨ Feature - 유저 정보 상세 조회에 수신동의 여부 필드 추가
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountUserCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/controller/query/AccountUserQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadUserUserDetailResponseDto.java
Labels: ✨ Feature

#155 🐞 BugFix - 사용자 주문 요약 조회 버그 수정
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderOverviewService.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
Labels: 🐞 BugFix

#156 ✨ Feature - 7.1.1 결제하기 API 구현
  http/order/OrderControllerHttpRequest.http
  http/payment/PaymentControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/core/dto/PaymentDto.java
  src/main/java/com/tookscan/tookscan/core/utility/RestClientUtil.java
  src/main/java/com/tookscan/tookscan/core/utility/TossPaymentUtil.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/payment/application/controller/command/.keep
  src/main/java/com/tookscan/tookscan/payment/application/controller/command/PaymentCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/payment/application/dto/request/.keep
  src/main/java/com/tookscan/tookscan/payment/application/dto/request/ConfirmPaymentRequestDto.java
  src/main/java/com/tookscan/tookscan/payment/application/service/.keep
  src/main/java/com/tookscan/tookscan/payment/application/service/ConfirmPaymentService.java
  src/main/java/com/tookscan/tookscan/payment/application/usecase/.keep
  src/main/java/com/tookscan/tookscan/payment/application/usecase/ConfirmPaymentUseCase.java
  src/main/java/com/tookscan/tookscan/payment/domain/Payment.java
  src/main/java/com/tookscan/tookscan/payment/domain/service/.keep
  src/main/java/com/tookscan/tookscan/payment/domain/service/PaymentService.java
  src/main/java/com/tookscan/tookscan/payment/domain/type/EPaymentMethod.java
  src/main/java/com/tookscan/tookscan/payment/repository/PaymentRepository.java
  src/main/java/com/tookscan/tookscan/payment/repository/mysql/PaymentJpaRepository.java
  src/main/java/com/tookscan/tookscan/payment/repository/mysql/PaymentRepositoryImpl.java
Labels: ✨ Feature

#158 ✨ Feature - 테스트 메일 발송 API 구현
  http/MailControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/core/constant/Constants.java
  src/main/java/com/tookscan/tookscan/core/listener/EmailListener.java
  src/main/java/com/tookscan/tookscan/core/utility/MailUtil.java
  src/main/java/com/tookscan/tookscan/mail/application/controller/command/MailCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/mail/application/dto/request/SendTestMailRequestDto.java
  src/main/java/com/tookscan/tookscan/mail/application/service/SendTestMailService.java
  src/main/java/com/tookscan/tookscan/mail/application/usecase/SendTestMailUseCase.java
  src/main/java/com/tookscan/tookscan/mail/event/EmailEvent.java
Labels: ✨ Feature

#160 ✨ Feature - 소셜로그인 시, 리다이렉트 하도록 기능 변경
  src/main/java/com/tookscan/tookscan/core/constant/Constants.java
  src/main/java/com/tookscan/tookscan/core/utility/HttpServletUtil.java
  src/main/java/com/tookscan/tookscan/security/config/SecurityConfig.java
  src/main/java/com/tookscan/tookscan/security/filter/RedirectUrlFilter.java
  src/main/java/com/tookscan/tookscan/security/handler/login/Oauth2SuccessHandler.java
Labels: ✨ Feature

#165 🐞 BugFix - SerialId UNIQUE 제약조건 삭제
  src/main/java/com/tookscan/tookscan/security/application/dto/request/SignUpDefaultRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/dto/request/SignUpOauthRequestDto.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpDefaultService.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpOauthService.java
  src/main/java/com/tookscan/tookscan/security/domain/mysql/Account.java
Labels: 🐞 BugFix

#166 ✨ Feature - 4.2.4 유저 상세 배송 정보 조회 API 구현
  src/main/java/com/tookscan/tookscan/core/utility/DeliveryTrackerUtil.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderUserQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadUserOrderDeliveryResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateGuestOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateUserOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderDeliveryService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadUserOrderDeliveryUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/type/EDeliveryDetailStatus.java
  src/main/java/com/tookscan/tookscan/order/domain/type/EDeliveryStatus.java
Labels: ✨ Feature

#168 🐞 BugFix - 테스트 메일 이미지 클릭 시 링크로 이동하는 버그 수정
  http/MailControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/core/utility/MailUtil.java
Labels: 🐞 BugFix

#172 🔨 Fix - 이메일 폼 CSS 인라인 형식으로 변경
  src/main/java/com/tookscan/tookscan/core/utility/MailUtil.java
Labels: 🔨 Fix

#174 🔨 Fix - 주문 상세 내역 조회에 user_info(name, email, phone_number) 필드 추가
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadGuestOrderDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadUserOrderDetailResponseDto.java
Labels: 🔨 Fix

#176 🔨 Fix - Integer에 NotBlank 어노테이션 적용 버그 수정
  src/main/java/com/tookscan/tookscan/payment/application/dto/request/ConfirmPaymentRequestDto.java
Labels: 🔨 Fix

#178 ✨ Feature - RestClient 결제에 관련한 예외처리 추가
  src/main/java/com/tookscan/tookscan/core/constant/Constants.java
  src/main/java/com/tookscan/tookscan/core/exception/error/ErrorCode.java
  src/main/java/com/tookscan/tookscan/core/utility/RestClientUtil.java
Labels: ✨ Feature

#180 🔨 Fix - 결제 오류 수정
  src/main/java/com/tookscan/tookscan/core/utility/TossPaymentUtil.java
Labels: 🔨 Fix

#184 🔨 Fix - 결제 날짜 파싱 오류 수정
  src/main/java/com/tookscan/tookscan/payment/application/service/ConfirmPaymentService.java
Labels: 🔨 Fix
