Repository TOOK-SCAN/TOOK-SCAN-Backend, pull requests merged in 2025-01, with the labels that each got.

#11 ✨ Feature - 휴대전화 인증 구현
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/domain/Group.java
  src/main/java/com/tookscan/tookscan/core/constant/Constants.java
  src/main/java/com/tookscan/tookscan/core/listener/SmsListener.java
  src/main/java/com/tookscan/tookscan/core/utility/RestClientUtil.java
  src/main/java/com/tookscan/tookscan/core/utility/S3Util.java
  src/main/java/com/tookscan/tookscan/core/utility/SmsUtil.java
  src/main/java/com/tookscan/tookscan/security/application/controller/AuthController.java
  src/main/java/com/tookscan/tookscan/security/application/service/IssueAuthenticationCodeService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ValidateAuthenticationCodeService.java
  src/main/java/com/tookscan/tookscan/security/event/CompletePhoneNumberValidationEvent.java
Labels: ✨ Feature

#17 🌏 Deploy - CICD 파이프라인 구축
  .github/workflows/dev-cicd.yml
  Dockerfile.dev
Labels: 🌏 Deploy

#19 🌏 Deploy - Pipeline 수정
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy

#20 🌏 Deploy - Pipeline 수정
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy

#21 ✨ Feature - 3.8 유저 간단 정보 조회 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/.keep
  src/main/java/com/tookscan/tookscan/account/application/controller/consumer/.keep
  src/main/java/com/tookscan/tookscan/account/application/controller/query/AccountQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/.keep
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadAccountBriefResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadAccountBriefService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/ReadAccountBriefUseCase.java
  src/main/java/com/tookscan/tookscan/account/domain/Admin.java
  src/main/java/com/tookscan/tookscan/account/domain/User.java
  src/main/java/com/tookscan/tookscan/security/domain/mysql/Account.java
Labels: ✨ Feature

#23 ✨ Feature - 3.9 유저 상세 정보 조회 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/query/AccountQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadAccountBriefResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadUserDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadUserDetailService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/ReadAccountBriefUseCase.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/ReadUserDetailUseCase.java
Labels: ✨ Feature

#27 ✨ Feature - 3.12 유저 정보 수정 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/UserCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateUserRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadAccountBriefResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadUserDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadUserSummaryResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadAccountBriefService.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadUserDetailService.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadUserSummaryService.java
  src/main/java/com/tookscan/tookscan/account/application/service/UpdateUserService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/UpdateUserUseCase.java
  src/main/java/com/tookscan/tookscan/account/domain/User.java
  src/main/java/com/tookscan/tookscan/account/domain/service/UserService.java
  src/main/java/com/tookscan/tookscan/address/dto/request/AddressRequestDto.java
Labels: ✨ Feature

#30 🐞 BugFix - 각 번호 별 인증코드의 고유성이 만족되지 않던 버그 수정
  src/main/java/com/tookscan/tookscan/security/application/service/IssueAuthenticationCodeService.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpOauthService.java
  src/main/java/com/tookscan/tookscan/security/application/usecase/IssueAuthenticationCodeUseCase.java
  src/main/java/com/tookscan/tookscan/security/domain/redis/AuthenticationCode.java
  src/main/java/com/tookscan/tookscan/security/domain/service/AuthenticationCodeService.java
Labels: 🐞 BugFix

#32 🌏 Deploy - 이미지 삭제에 있어서 정확한 이미지 명으로 변경
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy

#34 🐞 BugFix - 휴대폰 인증 시 계정 내 휴대폰 중복 여부를 검사하고있던 버그 수정
  src/main/java/com/tookscan/tookscan/account/application/controller/command/.keep
  src/main/java/com/tookscan/tookscan/core/exception/error/ErrorCode.java
  src/main/java/com/tookscan/tookscan/security/application/service/IssueAuthenticationCodeService.java
Labels: 🐞 BugFix

#40 ✨ Feature - 4.5 관리자 주문 메모 작성 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/CreateOrderMemoRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateOrderMemoService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/CreateOrderMemoUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
Labels: ✨ Feature

#46 ✨ Feature - 4.14 (관리자) 주문 정보 간단 조회 API 구현
  src/main/java/com/tookscan/tookscan/account/application/controller/query/AccountAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminOrderBriefResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadGuestOrderDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadUserOrderDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderBriefService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminOrderBriefUseCase.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustom.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustomImpl.java
Labels: ✨ Feature

#48 ✨ Feature - 4.2.6 (관리자) 주문 리스트 요약 조회 API 구현
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderGuestQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/CreateGuestOrderResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/CreateUserOrderResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminOrderBriefsResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminOrderSummariesResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadGuestOrderDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadUserOrderDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadUserOrderOverviewResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateGuestOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateUserOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderBriefsService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderSummariesService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadGuestOrderDetailService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminOrderBriefsUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminOrderSummariesUseCase.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadGuestOrderDetailUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Document.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
  src/main/java/com/tookscan/tookscan/order/domain/service/DocumentService.java
  src/main/java/com/tookscan/tookscan/order/domain/service/OrderService.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustom.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustomImpl.java
Labels: ✨ Feature

#50 ✨ Feature - 4.3.2 (관리자) 주문 상태 일괄 변경 API 구현
  src/main/java/com/tookscan/tookscan/core/dto/ResponseDto.java
  src/main/java/com/tookscan/tookscan/core/exception/type/CommonException.java
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrdersStatusRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrdersStatusService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/UpdateAdminOrdersStatusUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
  src/main/java/com/tookscan/tookscan/security/domain/type/ESecurityRole.java
Labels: ✨ Feature

#52 ✨ Feature - 4.5.1 (관리자) 주문 일괄 삭제 API 구현
  src/main/java/com/tookscan/tookscan/account/domain/Admin.java
  src/main/java/com/tookscan/tookscan/account/domain/Group.java
  src/main/java/com/tookscan/tookscan/account/domain/User.java
  src/main/java/com/tookscan/tookscan/account/domain/UserGroup.java
  src/main/java/com/tookscan/tookscan/message/domain/Message.java
  src/main/java/com/tookscan/tookscan/message/domain/MessageGroup.java
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteAdminOrdersService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/DeleteAdminOrdersUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Delivery.java
  src/main/java/com/tookscan/tookscan/order/domain/Document.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
  src/main/java/com/tookscan/tookscan/order/domain/OrderMemo.java
  src/main/java/com/tookscan/tookscan/order/domain/Pdf.java
  src/main/java/com/tookscan/tookscan/order/domain/PricePolicy.java
  src/main/java/com/tookscan/tookscan/payment/domain/Payment.java
  src/main/java/com/tookscan/tookscan/security/domain/mysql/Account.java
  src/main/java/com/tookscan/tookscan/term/domain/Term.java
Labels: ✨ Feature

#60 ✨ Feature - 3.4.3 (관리자) 사용자 그룹 지정 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/CreateAdminUserGroupRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadAdminUserOverviewResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/CreateAdminUserGroupService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/CreateAdminUserGroupUseCase.java
  src/main/java/com/tookscan/tookscan/account/domain/service/UserGroupService.java
  src/main/java/com/tookscan/tookscan/account/repository/UserGroupRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupJPARepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupRepositoryImpl.java
Labels: ✨ Feature

#62 🔨 Refactor - Repository 추상화
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/CreateAdminGroupRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/CreateAdminGroupService.java
  src/main/java/com/tookscan/tookscan/account/application/service/CreateAdminUserGroupService.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadAdminUserDetailService.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadAdminUserOverviewService.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadUserUserDetailService.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadUserUserSummaryService.java
  src/main/java/com/tookscan/tookscan/account/application/service/UpdateUserUserService.java
  src/main/java/com/tookscan/tookscan/account/domain/service/GroupService.java
  src/main/java/com/tookscan/tookscan/account/repository/AdminRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/GroupRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/UserRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/AdminJpaRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/AdminRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/AdminRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/GroupJpaRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/GroupRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupJpaRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserJpaRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/custom/UserRepositoryCustom.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateGuestOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateUserOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderDetailService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderOverviewService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateUserOrderScanService.java
  src/main/java/com/tookscan/tookscan/security/application/service/AdminSignUpDefaultService.java
  src/main/java/com/tookscan/tookscan/security/application/service/AuthenticateJsonWebTokenService.java
  src/main/java/com/tookscan/tookscan/security/application/service/AuthenticateUserNameService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ChangePasswordService.java
  src/main/java/com/tookscan/tookscan/security/application/service/CustomOauth2UserDetailService.java
  src/main/java/com/tookscan/tookscan/security/application/service/DeleteAccountService.java
  src/main/java/com/tookscan/tookscan/security/application/service/IssueAuthenticationCodeService.java
  src/main/java/com/tookscan/tookscan/security/application/service/LoginDefaultService.java
  src/main/java/com/tookscan/tookscan/security/application/service/LoginOauthService.java
  src/main/java/com/tookscan/tookscan/security/application/service/LogoutService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ReadAccountBriefService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ReadSerialIdAndProviderService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ReissueJsonWebTokenService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ReissuePasswordService.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpDefaultService.java
  src/main/java/com/tookscan/tookscan/security/application/service/SignUpOauthService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ValidateAuthenticationCodeService.java
  src/main/java/com/tookscan/tookscan/security/application/service/ValidateIdService.java
  src/main/java/com/tookscan/tookscan/security/repository/AccountRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/AuthenticationCodeHistoryRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/AuthenticationCodeRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/RefreshTokenRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/mysql/AccountJpaRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/mysql/AccountRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/AuthenticationCodeHistoryRedisRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/AuthenticationCodeHistoryRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/AuthenticationCodeRedisRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/AuthenticationCodeRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/RefreshTokenRedisRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/redis/RefreshTokenRepositoryImpl.java
Labels: 🔨 Refactor

#64 🐞 BugFix - 클래스명 변경이 추적에 포함되지 않는 버그로 인해 발생한 오류 해결
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupJPARepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupJpaRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/UserGroupRepositoryImpl.java
Labels: 🐞 BugFix

#55 ✨ Feature - 4.3.4 (관리자) 배송지 정보 수정 API 구현
  src/main/java/com/tookscan/tookscan/core/exception/error/ErrorCode.java
  src/main/java/com/tookscan/tookscan/order/application/controller/command/OrderAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/request/UpdateAdminOrderDeliveryRequestDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteAdminOrdersService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderSummariesService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrderDeliveryService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrdersStatusService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/UpdateAdminOrderDeliveryUseCase.java
  src/main/java/com/tookscan/tookscan/order/domain/Delivery.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
  src/main/java/com/tookscan/tookscan/order/domain/service/DeliveryService.java
  src/main/java/com/tookscan/tookscan/order/domain/service/OrderService.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustom.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustomImpl.java
Labels: ✨ Feature

#66 ✨ Feature - 3.2.5 (관리자) 그룹 간단 정보 조회 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/query/AccountAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadAdminGroupBriefResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/ReadAdminGroupBriefService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/ReadAdminGroupBriefUseCase.java
  src/main/java/com/tookscan/tookscan/account/repository/GroupRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/GroupRepositoryImpl.java
Labels: ✨ Feature

#68 ✨ Feature - 3.3.1 (관리자) 그룹 수정 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateAdminGroupRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/UpdateAdminGroupService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/UpdateAdminGroupUseCase.java
  src/main/java/com/tookscan/tookscan/account/domain/Group.java
  src/main/java/com/tookscan/tookscan/account/domain/service/GroupService.java
Labels: ✨ Feature

#70 ✨ Feature - 3.4.2 (관리자) 유저 정보 수정 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/UpdateAdminUserRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/UpdateAdminUserService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/UpdateAdminUserUseCase.java
  src/main/java/com/tookscan/tookscan/account/domain/User.java
  src/main/java/com/tookscan/tookscan/account/domain/service/UserService.java
Labels: ✨ Feature

#73 ✨ Feature - 3.5.1 (관리자) 그룹 삭제 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/service/DeleteAdminGroupService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/DeleteAdminGroupUseCase.java
  src/main/java/com/tookscan/tookscan/account/repository/GroupRepository.java
  src/main/java/com/tookscan/tookscan/account/repository/mysql/GroupRepositoryImpl.java
Labels: ✨ Feature

#76 ✨ Feature - 3.5.2 (관리자) 유저 삭제 API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/account/application/controller/command/AccountAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/account/application/dto/request/DeleteAdminUserRequestDto.java
  src/main/java/com/tookscan/tookscan/account/application/service/DeleteAdminUserService.java
  src/main/java/com/tookscan/tookscan/account/application/usecase/DeleteAdminUserUseCase.java
  src/main/java/com/tookscan/tookscan/account/domain/User.java
  src/main/java/com/tookscan/tookscan/security/repository/AccountRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/mysql/AccountJpaRepository.java
  src/main/java/com/tookscan/tookscan/security/repository/mysql/AccountRepositoryImpl.java
Labels: ✨ Feature

#77 🔨 Refactor - Order 도메인 Repository 추상화
  src/main/java/com/tookscan/tookscan/account/application/service/ReadAdminUserOverviewService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateAdminOrderMemoService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateGuestOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/CreateUserOrderService.java
  src/main/java/com/tookscan/tookscan/order/application/service/DeleteAdminOrdersService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderBriefService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderBriefsService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderDocumentsOverviewsService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderSummariesService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadGuestOrderDetailService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderDetailService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadUserOrderOverviewService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrderDeliveryService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateAdminOrdersStatusService.java
  src/main/java/com/tookscan/tookscan/order/application/service/UpdateUserOrderScanService.java
  src/main/java/com/tookscan/tookscan/order/domain/Order.java
  src/main/java/com/tookscan/tookscan/order/domain/OrderMemo.java
  src/main/java/com/tookscan/tookscan/order/domain/service/OrderService.java
  src/main/java/com/tookscan/tookscan/order/repository/DeliveryRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/DocumentRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/InitialDocumentRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/PdfRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/PricePolicyRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DeliveryJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DeliveryRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DocumentJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/DocumentRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/InitialDocumentJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/InitialDocumentRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderMemoRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/PdfJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/PdfRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/PricePolicyJpaRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/PricePolicyRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/custom/OrderRepositoryCustom.java
Labels: 🔨 Refactor

#82 ✨ Feature - 8.2.1 (관리자) 약관 조회 API 구현
  http/term/TermControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/term/application/controller/query/TermAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/term/application/dto/response/.keep
  src/main/java/com/tookscan/tookscan/term/application/dto/response/ReadAdminTermOverviewResponseDto.java
  src/main/java/com/tookscan/tookscan/term/application/service/CreateAdminTermService.java
  src/main/java/com/tookscan/tookscan/term/application/service/ReadAdminTermOverviewService.java
  src/main/java/com/tookscan/tookscan/term/application/usecase/ReadAdminTermOverviewUseCase.java
  src/main/java/com/tookscan/tookscan/term/domain/service/.keep
  src/main/java/com/tookscan/tookscan/term/repository/TermRepository.java
  src/main/java/com/tookscan/tookscan/term/repository/mysql/TermJpaRepository.java
  src/main/java/com/tookscan/tookscan/term/repository/mysql/TermRepositoryImpl.java
  src/main/java/com/tookscan/tookscan/term/repository/redis/.keep
Labels: ✨ Feature

#84 ✨ Feature - 8.2.2 약관 조회 API 구현
  http/auth/AuthControllerHttpRequest.http
  http/term/TermControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/term/application/controller/query/.keep
  src/main/java/com/tookscan/tookscan/term/application/controller/query/TermUserQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/term/application/dto/response/ReadUserTermOverviewResponseDto.java
  src/main/java/com/tookscan/tookscan/term/application/service/ReadUserTermOverviewService.java
  src/main/java/com/tookscan/tookscan/term/application/usecase/ReadUserTermOverviewUseCase.java
Labels: ✨ Feature

#88 ✨ Feature - 8.5.1 (관리자) 약관 삭제 API 구현
  http/term/TermControllerHttpRequest.http
  src/main/java/com/tookscan/tookscan/term/application/controller/command/TermAdminCommandV1Controller.java
  src/main/java/com/tookscan/tookscan/term/application/service/DeleteAdminTermService.java
  src/main/java/com/tookscan/tookscan/term/application/usecase/DeleteAdminTermUseCase.java
  src/main/java/com/tookscan/tookscan/term/repository/TermRepository.java
  src/main/java/com/tookscan/tookscan/term/repository/mysql/TermJpaRepository.java
  src/main/java/com/tookscan/tookscan/term/repository/mysql/TermRepositoryImpl.java
Labels: ✨ Feature

#90 🐞 BugFix - 병합 시 중복 코드 삽입으로 인한 버그 수정
  src/main/java/com/tookscan/tookscan/term/application/controller/command/TermAdminCommandV1Controller.java
Labels: 🐞 BugFix

#91 ✨ Feature - 4.2.10 (관리자) 주문 상세 배송 조회 API 구현
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadAdminUserDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadUserUserDetailResponseDto.java
  src/main/java/com/tookscan/tookscan/account/application/dto/response/ReadUserUserSummaryResponseDto.java
  src/main/java/com/tookscan/tookscan/address/dto/response/AddressResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/controller/query/OrderAdminQueryV1Controller.java
  src/main/java/com/tookscan/tookscan/order/application/dto/response/ReadAdminOrderDeliveryOverviewResponseDto.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadAdminOrderDeliveryOverviewService.java
  src/main/java/com/tookscan/tookscan/order/application/service/ReadGuestOrderDetailService.java
  src/main/java/com/tookscan/tookscan/order/application/usecase/ReadAdminOrderDeliveryOverviewUseCase.java
  src/main/java/com/tookscan/tookscan/order/repository/OrderRepository.java
  src/main/java/com/tookscan/tookscan/order/repository/mysql/OrderRepositoryImpl.java
Labels: ✨ Feature
